services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app/frontend-app
    command: >
      ash -c "npm install && npm run dev"
    tty: true
