services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend:delegated
      - /app/frontend/node_modules
    working_dir: /app/frontend
    tty: true
