version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend:delegated
      - /app/frontend/node_modules
    working_dir: /app/frontend
    tty: true

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    tty: true

  dev:
    build:
      context: .
      dockerfile:  ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - frontend
      - backend
    command: sleep infinity
